### PR TITLE
Fix resolution of sources based on abspath

### PR DESCRIPTION
**Pull request by brandonpayton**

### CODE REVIEW

**Comment by brandonpayton** [comment]
OK, now that we're successfully failing, we can commit the fix and demonstrate that it indeed fixes the issue.

**Comment by aidvu** [comment]
Let's add some docs on running `phpcs` locally.

**Comment by brandonpayton** [comment]
> Let's add some docs on running the phpcs locally.

Just `phpcs` or `phpunit` too? I'd like to be able to do the latter but haven't worked out how with this setup.

**Comment by brandonpayton** [comment]
...asking because I wasn't sure if it was a random comment, related to this PR, or related to the large number of commits I made to the last PR to get passing tests :)

**Comment by brandonpayton** [comment]
I'm going to merge this and make a note to follow up with developer notes on Monday.

**Comment by aidvu** [comment]
Just for `phpcs`. Making tests run is harder. :) I'm fine running it on Travis CI only for now.

**Comment by brandonpayton** [comment]
Thanks again for pointing out this terrible bug, @aidvu!

**Pull request merged**
